# Generated by Django 5.1.1 on 2024-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedevent',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishedevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishedevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
